- name: install python-pip
  apt: name=python-pip state=installed update_cache=True

- name: install webapp dependencies
  pip: requirements=/app/requirements.txt
  register: pip_status

- name: reload supervisord
  command: supervisorctl reload
  when: pip_status.changed

- name: wait 5 seconds... (to respawn processess)
  pause: seconds=5